version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
      - "8000:8000"
    volumes:
      - ".:/var/www/html"  
    networks:
      - app
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    depends_on:
      - db
      - redis
  frontend:
    image: "node"
    volumes:
      - "./client:/var/www/html"
    working_dir: "/var/www/html"
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    
  db:
    image: "mysql:8.0"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "appdb:/var/lib/mysql"
    networks:
      - app

  # Redis.
  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "appredis:/data"
    networks:
      - app

  ## PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "5005:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app

# Network.
networks:
  app:
    driver: bridge

volumes:
  appdb:
    driver: local
  appredis:
    driver: local
